### ISSUE TITLE
Error: Connection ended: possibly due to an authentication failure

### ISSUE THREAD

**Issue by tuxpower** [FGRibreau/node-amqp-tool#18]
I'm running amqp-tool against rabbitmq 3.2.4 using an authenticated user but always fails. Logging in the web UI works though:
```
amqp-tool -vvvv --host localhost --port 32781 -u jgaspar -p 123456 -q test --count 1 --export dump.json
RabbitMQ :: error Error: Connection ended: possibly due to an authentication failure.
    at Connection.<anonymous> (/usr/lib/node_modules/amqp-tool/node_modules/amqp/lib/connection.js:283:26)
    at emitNone (events.js:106:13)
    at Connection.emit (events.js:208:7)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
RabbitMQ connection closed :: close false
```

When not specifying a user it works fine with default one (guest/guest). Rabbitmq is running inside a vagrant box and I'm forwarding the port, hence it's using 32781.

**Comment by FGRibreau** [comment]
It seems to be related with your RabbitMQ user configuration, check that you did allow the right host access for this user in RabbitMQ policy panel.
