### ISSUE TITLE
TypeError: Cannot call method 'bind' of undefined

### ISSUE THREAD

**Issue by Yemsheng** [FGRibreau/node-amqp-tool#7]
I run this command "amqp-tool --host localhost -u guest -p guest -q queue1 --count 5 --import dump.json".    
It comes this error.
```
/usr/local/lib/node_modules/amqp-tool/bin/amqp-tool:133
    streamController.close(stream, conn.destroySoon.bind(conn));
                                                    ^
TypeError: Cannot call method 'bind' of undefined
    at stopImport (/usr/local/lib/node_modules/amqp-tool/bin/amqp-tool:133:53)
    at importMsg (/usr/local/lib/node_modules/amqp-tool/bin/amqp-tool:128:7)
    at /usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:99:35
    at Lazy.<anonymous> (/usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:74:37)
    at Lazy.emit (events.js:98:17)
    at Lazy.<anonymous> (/usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:74:22)
    at Lazy.emit (events.js:95:17)
    at yieldTo (/usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:181:18)
    at Function.<anonymous> (/usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:219:27)
    at Lazy.<anonymous> (/usr/local/lib/node_modules/amqp-tool/node_modules/lazy/lazy.js:187:21)
```

**Comment by FGRibreau** [comment]
`destroySoon` does not seem to be available indeed. I don't have the time to fix this but don't hesitate to send a PR for this and I will merge it!
